apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bajwa-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ index .Values.hosts 0 }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: bajwa-tech-tls
    hosts:
    - {{ index .Values.hosts 0 }}
